version: '3.8'

services:
  frontend:
    build:
      context: ./src
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./weather-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      # Add any other environment variables here (like email credentials)
    volumes:
      - .:/usr/src/app


  
